FROM python:3.11-slim

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ .
COPY database.sqlite /app/../database.sqlite

EXPOSE 5000

CMD ["python", "app.py"]
